kind = "web"
previewPath = "/"
title = "Mani"
version = "1.0.0"
id = "artifacts/mani"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21970

[services.development]
run = "pnpm --filter @workspace/mani run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mani", "run", "build" ]
publicDir = "artifacts/mani/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21970"
BASE_PATH = "/"
